name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build

      - name: Run tests
        run: dotnet test

      - name: Publish Console App
        run: dotnet publish apps/Thomas.Siest.ObjectDetection.Console/Thomas.Siest.ObjectDetection.Console.csproj --configuration Release --output ./output --runtime win-x64 --self-contained true

      - name: Upload Console App Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ObjectDetection.Console
          path: ./output
